schema-version: v1
kind: plugin
metadata:
  name: stk-plugin-angular-basic
  display-name: stk-plugin-angular-basic
  description: Create an Basic Angular App
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md

